### ISSUE TITLE
Podium fails to build

### ISSUE THREAD

**Issue by ryannix123** [sa-mw-dach/podium#16]
Hello,

I'm running OKD 3.11 and I ran into an issue when deploying Podium.

Cloning "https://github.com/sa-mw-dach/podium.git " ...
	Commit:	87118ba6e8c830c95b47f8bdba44bf11f57fd68b (updated mozaik party template)
	Author:	ktenzer <keith.tenzer@gmail.com>
	Date:	Fri Oct 2 22:16:22 2020 +0000
npm ERR! 
npm ERR! Failed at the podium-dashboard@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2020-10-06T15_30_26_356Z-debug.log
error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/openshift/nodejs@sha256:1175006938852dff3ac21cdcab0939b65e0499a6ba0c4d1586869b3f31465f3f

**Comment by ktenzer** [comment]
Can you provide some more info? Are you deploying through operator hub? Manually? Can you provide output from logs? The operator does not do a docker build so not sure what you are trying to do?

**Comment by ryannix123** [comment]
Hi Keith,

I was trying to deploy Podium manually into our OKD 3.11.

- Ryan

**Comment by ryannix123** [comment]
Another error I received while deploying Mattermost manually:

```
Error from server (Forbidden): securitycontextconstraints.security.openshift.io is forbidden: User "rtn361@ads.northwestern.edu" cannot create securitycontextconstraints.security.openshift.io at the cluster scope: no RBAC policy matched
C02ST4LLH03Q:podium rtn361$ oc process -f jitsi/yaml/jitsi_meet_template.yaml -p TIMEZONE=America/Chicago -p APPLICATION_DOMAIN=apps.cloudapps.northwestern.edu-p NAMESPACE=podium |oc create -f -
```

**Comment by ktenzer** [comment]
yeah we havent been maintaining a manual deployment. It is kinda just a guideline. I suggest using Operator that is why we have it, it works. The errors indicate not enough permissions as for mattermost it needs to be able to create a scc (security constraint).

**Comment by ktenzer** [comment]
i will checkin something shortly that lets you use operator without OLM which isnt in OKD 3.x

**Comment by ktenzer** [comment]
Ok I added some yaml file to deploy podium-operator manually. This should work for OCP/OKD 3 since there is no operatorhub available. Follow documentation: create a label for the jvb and then at bottom are steps to deploy operator manually https://github.com/sa-mw-dach/podium/blob/master/podium-operator/README.md

**Comment by ryannix123** [comment]
Thanks, @ktenzer . I'll try these instructions out tomorrow and you let you know how it goes. 

This is really a great project.

**Comment by ryannix123** [comment]
@ktenzer So far, so good!

I'm having trouble deploying Jitsi, and I'm wondering if it's related to Jitsi running as root? Since I'm not running Podman on my instance of OKD, should I use @shetze 's patch and create my own my non-root Docker image on Quay?

**Comment by ktenzer** [comment]
No nothing runs as root that gets deployed via Operator, all the images the
Operator uses are non root.

If you are building your own jitsi images yes under jitsi folder is README
and it explains that. You have to use the patch. Not sure why you
arent using the Operator?

Keith

**Comment by ryannix123** [comment]
I can't use the Operator because we're still using OKD 3.11 for at least the foreseeable future.
